# Generated by Django 4.2.3 on 2023-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="format: not required, only one address is_default=True",
                verbose_name="company default address",
            ),
        ),
    ]
